export const NATION_DATA = [
  { "name": "USA", "lat": 38, "lon": -97 },
  { "name": "Kanada", "lat": 56, "lon": -106 },
  { "name": "Brasilien", "lat": -14, "lon": -51 },
  { "name": "Argentinien", "lat": -38, "lon": -63 },
  { "name": "Mexiko", "lat": 23, "lon": -102 },
  { "name": "Vereinigtes Königreich", "lat": 55, "lon": -3 },
  { "name": "Frankreich", "lat": 46, "lon": 2 },
  { "name": "Deutschland", "lat": 51, "lon": 10 },
  { "name": "Spanien", "lat": 40, "lon": -3 },
  { "name": "Italien", "lat": 41, "lon": 12 },
  { "name": "Russland", "lat": 61, "lon": 105 },
  { "name": "Türkei", "lat": 39, "lon": 35 },
  { "name": "Ukraine", "lat": 48, "lon": 31 },
  { "name": "Polen", "lat": 52, "lon": 19 },
  { "name": "China", "lat": 35, "lon": 104 },
  { "name": "Indien", "lat": 20, "lon": 77 },
  { "name": "Japan", "lat": 36, "lon": 138 },
  { "name": "Südkorea", "lat": 36, "lon": 128 },
  { "name": "Indonesien", "lat": -5, "lon": 120 },
  { "name": "Iran", "lat": 32, "lon": 53 },
  { "name": "Saudi-Arabien", "lat": 25, "lon": 45 },
  { "name": "Ägypten", "lat": 26, "lon": 30 },
  { "name": "Nigeria", "lat": 9, "lon": 8 },
  { "name": "Südafrika", "lat": -30, "lon": 25 },
  { "name": "Australien", "lat": -25, "lon": 133 },
  { "name": "Abbasiden", "lat": 33, "lon": 44 },
  { "name": "Umayyaden", "lat": 37, "lon": -4 },
  { "name": "Osmanisches Reich", "lat": 40, "lon": 30 },
  { "name": "Byzantinisches Reich", "lat": 39, "lon": 27 },
  { "name": "Heiliges Römisches Reich", "lat": 49, "lon": 10 },
  { "name": "Fränkisches Reich", "lat": 48, "lon": 4 },
  { "name": "Wikinger", "lat": 60, "lon": 10 },
  { "name": "Kiewer Rus", "lat": 50, "lon": 30 },
  { "name": "Mongolisches Reich", "lat": 47, "lon": 103 },
  { "name": "Goldene Horde", "lat": 47, "lon": 47 },
  { "name": "Timuriden", "lat": 40, "lon": 65 },
  { "name": "Safawiden", "lat": 34, "lon": 51 },
  { "name": "Delhi-Sultanat", "lat": 28, "lon": 77 },
  { "name": "Ming-Dynastie", "lat": 32, "lon": 118 },
  { "name": "Yuan-Dynastie", "lat": 39, "lon": 116 },
  { "name": "Japanisches Shogunat", "lat": 35, "lon": 136 },
  { "name": "Joseon Korea", "lat": 38, "lon": 127 },
  { "name": "Mali-Reich", "lat": 17, "lon": -4 },
  { "name": "Songhai-Reich", "lat": 16, "lon": -2 },
  { "name": "Aztekenreich", "lat": 19, "lon": -99 },
  { "name": "Inka-Reich", "lat": -13, "lon": -76 },
  { "name": "Mayareiche", "lat": 17, "lon": -90 },
  { "name": "Khmer-Reich", "lat": 12, "lon": 104 },
  { "name": "Majapahit-Reich", "lat": -7, "lon": 112 },
  { "name": "Kreuzfahrerstaaten", "lat": 31, "lon": 35 },
  { "name": "Papststaat", "lat": 42, "lon": 12 },
  { "name": "Polnisch-Litauische Union", "lat": 53, "lon": 23 },
  { "name": "Ungarisches Königreich", "lat": 47, "lon": 19 },
  { "name": "Serbisches Reich", "lat": 43, "lon": 21 },
  { "name": "Bulgarisches Reich", "lat": 42, "lon": 25 },
  { "name": "Palästina", "lat": 31.5, "lon": 35.2 },
  { "name": "AFGHANISTAN", "lat": 33, "lon": 65 }
];
